import { MyTheme } from "@/constants/Colors";
// Du importierst jetzt alle Icons aus einem einzigen Paket!
import {
  HouseIcon,
  UsersThreeIcon,
  BookIcon,
  ShoppingBagIcon,
  UserIcon,
  QuestionIcon,
  CaretLeftIcon,
  BellIcon,
  GearIcon,
  PlusIcon,
  FadersIcon,
  CheckIcon,
  XIcon,
  EyeIcon,
  EyeClosedIcon,
  CheckCircleIcon,
  InfoIcon,
  LightbulbIcon,
  MagnifyingGlassIcon,
  PaperPlaneRightIcon,
  PencilSimpleIcon,
  ShareNetworkIcon,
  ChartBarIcon,
  TrophyIcon,
  WalletIcon,
  LockKeyIcon,
  ChatCircleIcon,
  HeartIcon,
  BookmarkSimpleIcon,
  DotsThreeVerticalIcon,
  CaretRightIcon,
  TrashIcon,
  FolderPlusIcon,
  TimerIcon,
  FireIcon,
  DiamondIcon,
  ProhibitIcon,
  CalendarBlankIcon,
  MusicNotesIcon,
  CoffeeIcon,
  DeviceMobileIcon,
  GiftIcon,
  BarbellIcon,
  SunIcon,
  RobotIcon,
  BedIcon,
  ShieldCheckIcon,
  LinkIcon,
  StarIcon,
  MoonIcon,
  GlobeIcon,
  HardDrivesIcon,
  ShieldSlashIcon,
  EnvelopeIcon,
  FileTextIcon,
  UserMinusIcon,
  BicycleIcon,
  CameraIcon,
  SpotifyLogoIcon,
  AtIcon
} from "phosphor-react-native";

// Hilfsfunktion, damit du "outline" weiterhin in deiner App nutzen kannst,
// es aber für Phosphor in "regular" oder "fill" übersetzt wird.
const getWeight = (outline) => (outline ? "regular" : "fill");

export const IconMap = {
  // Navigation Tabs
  home: ({ outline, ...props }) => <HouseIcon weight={getWeight(outline)} {...props} />,
  communities: ({ outline, ...props }) => <UsersThreeIcon weight={getWeight(outline)} {...props} />,
  tasks: ({ outline, ...props }) => <BookIcon weight={getWeight(outline)} {...props} />,
  shop: ({ outline, ...props }) => <ShoppingBagIcon weight={getWeight(outline)} {...props} />,
  profile: ({ outline, ...props }) => <UserIcon weight={getWeight(outline)} {...props} />,
  help: (props) => <QuestionIcon weight="regular" {...props} />,

  // Toolbar
  back: (props) => <CaretLeftIcon weight="bold" {...props} />, // Back-Pfeile sehen in "bold" oft besser aus
  notifications: (props) => <BellIcon weight="regular" {...props} />,
  settings: (props) => <GearIcon weight="regular" {...props} />,

  // UI
  add: (props) => <PlusIcon weight="bold" {...props} />,
  filter: (props) => <FadersIcon weight="regular" {...props} />,
  checkmark: (props) => <CheckIcon weight="bold" {...props} />,
  close: (props) => <XIcon weight="bold" {...props} />,
  eyeOpen: (props) => <EyeIcon weight="regular" {...props} />,
  eyeClosed: (props) => <EyeClosedIcon weight="regular" {...props} />,
  checkmarkCircle: (props) => <CheckCircleIcon weight="regular" {...props} />,
  infoCircle: (props) => <InfoIcon weight="regular" {...props} />,
  bulb: (props) => <LightbulbIcon weight="regular" {...props} />,
  search: (props) => <MagnifyingGlassIcon weight="bold" {...props} />,
  send: (props) => <PaperPlaneRightIcon weight="fill" {...props} />,
  pencil: (props) => <PencilSimpleIcon weight="regular" {...props} />,
  share: (props) => <ShareNetworkIcon weight="regular" {...props} />,
  statsChart: (props) => <ChartBarIcon weight="regular" {...props} />,
  trophy: (props) => <TrophyIcon weight="fill" {...props} color={MyTheme.gold} />, // Hier passt Fill oder Duotone super!
  wallet: (props) => <WalletIcon weight="regular" {...props} />,
  lock: (props) => <LockKeyIcon weight="regular" {...props} />,
  plane: (props) => <PaperPlaneRightIcon weight="regular" {...props} />,
  chat: (props) => <ChatCircleIcon weight="regular" {...props} />,
  heart: ({ outline, ...props }) => <HeartIcon weight={getWeight(outline)} {...props} />,
  bookmark: ({ outline, ...props }) => <BookmarkSimpleIcon weight={getWeight(outline)} {...props} />,
  dots: (props) => <DotsThreeVerticalIcon weight="bold" {...props} />,
  right: (props) => <CaretRightIcon weight="bold" {...props} />,
  trash: (props) => <TrashIcon weight="regular" {...props} />,

  // Placeholders (Kategorien)
  newFolder: (props) => <FolderPlusIcon weight="regular" {...props} />,
  timer: (props) => <TimerIcon weight="regular" {...props} />,
  fire: (props) => <FireIcon weight="regular" {...props} />,
  gem: (props) => <DiamondIcon weight="regular" {...props} />,
  ban: (props) => <ProhibitIcon weight="regular" {...props} />,
  calendar: (props) => <CalendarBlankIcon weight="regular" {...props} />,
  music: (props) => <MusicNotesIcon weight="regular" {...props} />,
  shopping: (props) => <ShoppingBagIcon weight="regular" {...props} />,
  shoppingCat: (props) => <ShoppingBagIcon weight="regular" {...props} />,
  mail: (props) => <EnvelopeIcon weight="regular" {...props} />,
  coffeeCat: (props) => <CoffeeIcon weight="regular" {...props} />,
  techCat: (props) => <DeviceMobileIcon weight="regular" {...props} />,
  giftCat: (props) => <GiftIcon weight="regular" {...props} />,
  dumbbell: (props) => <BarbellIcon weight="regular" {...props} />,
  sun: (props) => <SunIcon weight="regular" {...props} />,
  robot: (props) => <RobotIcon weight="regular" {...props} />,
  book: (props) => <BookIcon weight="regular" {...props} />,
  candy: (props) => <GiftIcon weight="regular" {...props} />, // Phosphor hat keine Candy-Cane, Gift oder Confetti ist hier eine gute Alternative
  bed: (props) => <BedIcon weight="regular" {...props} />,
  user: (props) => <UserIcon weight="regular" {...props} />,
  shield: (props) => <ShieldCheckIcon weight="regular" {...props} />,
  link: (props) => <LinkIcon weight="regular" {...props} />,
  bell: (props) => <BellIcon weight="regular" {...props} />,
  star: (props) => <StarIcon weight="regular" {...props} />,
  moon: (props) => <MoonIcon weight="regular" {...props} />,
  globe: (props) => <GlobeIcon weight="regular" {...props} />,
  hardDrive: (props) => <HardDrivesIcon weight="regular" {...props} />,
  shieldOff: (props) => <ShieldSlashIcon weight="regular" {...props} />,
  fileText: (props) => <FileTextIcon weight="regular" {...props} />,
  userX: (props) => <UserMinusIcon weight="regular" {...props} />,
  bicycle: (props) => <BicycleIcon weight="regular" {...props} />,
  camera: (props) => <CameraIcon weight="regular" {...props} />,
  spotify: (props) => <SpotifyLogoIcon weight="fill" {...props} />, // Logos immer filled
  at: (props) => <AtIcon weight="regular" {...props} />
};
