export const APP_EVENTS = {
  // Social
  LIKE_POST: "LIKE_POST",
  ADD_FRIEND: "ADD_FRIEND",
  SHARE_PROFILE: "SHARE_PROFILE",
  SHARE_POST: "SHARE_POST",
  POST_COMMENT: "POST_COMMENT",

  // Progression
  OPEN_CHEST: "OPEN_CHEST",
  LEVEL_UP: "LEVEL_UP",
  COMPLETE_TASK: "COMPLETE_TASK",

  // Customization
  EQUIP_BADGE: "EQUIP_BADGE",
  EQUIP_FRAME: "EQUIP_FRAME",
  UNLOCK_ITEM: "UNLOCK_ITEM",

  // App Engagement
  APP_OPEN: "APP_OPEN",
};